version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 # or whichever version you're using
  build:
    commands:
      - echo Building the project...
      - sam build
  post_build:
    commands:
      - echo Deploying the application...
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --s3-bucket sam-bucket-jonathan --parameter-overrides SQSQueueArn="arn:aws:sqs:us-east-1:288761751518:Jonathan-UploadsNotificationQueue"
      # - sam deploy --template-file .aws-sam/build/template.yaml \
      #              --stack-name your-stack-name \
      #              --capabilities CAPABILITY_IAM \
      #              --region your-region \
      #              --no-confirm-changeset \
      #              --no-fail-on-empty-changeset
artifacts:
  files:
    - '**/*'
