version = 0.1
[default.deploy.parameters]
stack_name = "sqs-sns-cicd"
resolve_s3 = false
s3_prefix = "sqs-sns-cicd"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "SQSQueueArn=\"arn:aws:sqs:us-east-1:288761751518:Jonathan-UploadsNotificationQueue"
image_repositories = []